### ISSUE TITLE
Testrail setup needs casandra server details

### ISSUE THREAD

**Issue by Babu5394** [sergiochoo/testrail-helm-chart#1]
do you have any idea on this one?
![image](https://user-images.githubusercontent.com/93255287/164458051-a3656b56-b0d8-4081-8212-dce6532552e3.png)

I could see they integrated cassandra recently. Are you working on this one to integrate into your helmcharts?

**Comment by sergiochoo** [comment]
@Babu5394 nope.
I don't have time to update this chart.
If you want, you can contribute. I will approve the pull request

**Comment by Babu5394** [comment]
Not able to add my code.

**Comment by sergiochoo** [comment]
Added Cassandra support to the chart.
